### ISSUE TITLE
Remove copyleft licence GPLv3

### ISSUE THREAD

**Issue by Apep-the-snek** [LiquidZulu/youtube-scripts#1]
all software licenses are null and void anyways, they are not real contracts, so i suggest to remove that bloat.

**Comment by LiquidZulu** [comment]
Without the license, it will be assumed by positive law courts to be all rights reserved, this is an implicit threat against people who want to copy the documents in this repository which I can easily avoid by just licensing it.

**Comment by Apep-the-snek** [comment]
But isn't it a threat that they can't make it into a binary without providing source code too then? You could state that this is public domain instead, could you not?
